import { Member } from "@/types/member";

export const mockMembers: Member[] = [
  {
    id: "1",
    firstName: "Emma",
    lastName: "Johnson",
    email: "emma.johnson@example.com",
    dateJoined: new Date("2024-01-15"),
    dateOfBirth: new Date("1992-05-20"),
  },
  {
    id: "2",
    firstName: "Michael",
    lastName: "Chen",
    email: "michael.chen@example.com",
    dateJoined: new Date("2024-02-03"),
    dateOfBirth: new Date("1988-11-08"),
  },
  {
    id: "3",
    firstName: "Sarah",
    lastName: "Williams",
    email: "sarah.williams@example.com",
    dateJoined: new Date("2024-03-12"),
    dateOfBirth: new Date("1995-07-14"),
  },
  {
    id: "4",
    firstName: "David",
    lastName: "Martinez",
    email: "david.martinez@example.com",
    dateJoined: new Date("2024-04-22"),
    dateOfBirth: new Date("1990-03-30"),
  },
  {
    id: "5",
    firstName: "Lisa",
    lastName: "Anderson",
    email: "lisa.anderson@example.com",
    dateJoined: new Date("2024-05-18"),
    dateOfBirth: new Date("1985-09-25"),
  },
  {
    id: "6",
    firstName: "James",
    lastName: "Taylor",
    email: "james.taylor@example.com",
    dateJoined: new Date("2024-06-07"),
    dateOfBirth: new Date("1993-12-02"),
  },
  {
    id: "7",
    firstName: "Maria",
    lastName: "Garcia",
    email: "maria.garcia@example.com",
    dateJoined: new Date("2024-07-21"),
    dateOfBirth: new Date("1991-04-18"),
  },
  {
    id: "8",
    firstName: "Robert",
    lastName: "Brown",
    email: "robert.brown@example.com",
    dateJoined: new Date("2024-08-14"),
    dateOfBirth: new Date("1987-08-09"),
  },
  {
    id: "9",
    firstName: "Jennifer",
    lastName: "Davis",
    email: "jennifer.davis@example.com",
    dateJoined: new Date("2024-09-05"),
    dateOfBirth: new Date("1994-06-22"),
  },
  {
    id: "10",
    firstName: "Christopher",
    lastName: "Wilson",
    email: "chris.wilson@example.com",
    dateJoined: new Date("2024-10-11"),
    dateOfBirth: new Date("1989-01-17"),
  },
];
